export {default as Header} from "./Header"
export {default as Footer} from "./Footer"
export {default as Modal} from "./Modal"
export {default as Slider} from "./Slider"
export {default as Title} from "./Title"
export {default as Work} from "./Work"
export {default as Price} from "./Price"
export {default as Quote} from "./Quote"
export {default as News} from "./News"
export {default as Mail} from "./Mail"


export {default as HeaderMobile} from "./Mobile/HeaderMobile"
export {default as TitleMobile} from "./Mobile/TitleMobile"
export {default as AboutMobile} from "./Mobile/AboutMobile"
export {default as EdgesMobile} from "./Mobile/EdgesMobile"
export {default as WorkMobile} from "./Mobile/WorkMobile"
export {default as MailMobile} from "./Mobile/MailMobile"
export {default as AddressMobile} from "./Mobile/AddressMobile"
export {default as FooterMobile} from "./Mobile/FooterMobile"