export {default as Header} from "./Header"
export {default as Footer} from "./Footer"
export {default as Modal} from "./Modal"
export {default as Slider} from "./Slider"
export {default as Title} from "./Title"
export {default as Work} from "./Work"
export {default as Price} from "./Price"
export {default as Quote} from "./Quote"
export {default as News} from "./News"
export {default as Mail} from "./Mail"


export {default as HeaderMobile} from "./Mobile/HeaderMobile"
export {default as SliderMobile} from "./Mobile/SliderMobile"
export {default as FooterMobile} from "./Mobile/FooterMobile"
export {default as TitleMobile} from "./Mobile/TitleMobile"
export {default as WorkMobile} from "./Mobile/WorkMobile"
export {default as PriceMobile} from "./Mobile/PriceMobile"
export {default as QuoteMobile} from "./Mobile/QuoteMobile"
export {default as NewsMobile} from "./Mobile/NewsMobile"
export {default as MailMobile} from "./Mobile/MailMobile"